#pll calls
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 0.1  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 0.5  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 1  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 1 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 4  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 0  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 0.2  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 3 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 0.7  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 2  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.8 --lmbd 10  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 5 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 0.1  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 0.5  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 1  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 7 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 4  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 0  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 0.2  &
wait
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset karate --method lmnn --K 11 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 0.7  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 2  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.7 --lmbd 10  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 1 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 0.1  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 0.5  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 1  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 4  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 3 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 0  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 0.2  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 0.7  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 5 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 2  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.5 --lmbd 10  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 0.1  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 7 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 0.5  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 1  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 4  &
wait
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset football --method lmnn --K 11 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 0  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 0.2  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 0.7  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 1 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 2  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.3 --lmbd 10  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 0.1  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 3 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 0.5  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 1  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 4  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 5 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 0  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.2 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 0.2  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 0.7  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 2  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 7 --reg 0.9 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.1 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.2 --lmbd 10  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.3 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.5 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 0.1  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.7 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 0.5  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.8 --lmbd 10  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 0  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 0.1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 0.2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 0.5  &
wait
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 0.7  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 1  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 2  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 4  &
python3 learn-metric.py --dataset polbooks --method lmnn --K 11 --reg 0.9 --lmbd 10  &
